name: Deploy helm chart to Kubernetes

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
            
    - name: 'Deploy chart'
      uses: 'deliverybot/helm@master'
      with:

        # What to name the release
        release: 'webhook-receiver'

        # The namespace into which to deploy the chart
        namespace: 'webhook-receiver'

        # Either "helm3" or "helm" (if you've not migrated away from Tiller yet!)
        helm: 'helm3'

        # Name of the helm chart
        chart: 'webhook-receiver'

        # Use any helm chart repository here
        repository: https://funkypenguins-geek-cookbook.github.io/helm-webhook-receiver

        # Insert your values.yaml overrides here, indented as you would in a regular YAML file
        values: |
        #   image:
        #     repository:   <whatever>/<whatever>:<tag>

      # Deployment will use the kubeconfig secret you created in the repo
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'